% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Oct-2017 17:48:24
%  MATLAB version: 9.2.0.556344 (R2017a)
% -------------------------------------------------------------------
saveVarsMat = load('Recognition001_Digits.mat');

imgTestAll = saveVarsMat.imgTestAll; % <784x10000 double> too many elements

imgTrainAll = saveVarsMat.imgTrainAll; % <784x60000 double> too many elements

lblTestAll = saveVarsMat.lblTestAll; % <10000x1 double> too many elements

lblTrainAll = saveVarsMat.lblTrainAll; % <60000x1 double> too many elements

clear saveVarsMat;
